[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = --basetemp=outputs/pytest-temp
cache_dir = outputs/pytest-cache
norecursedirs =
    .git
    .pytest_cache
    venv
    outputs
